In [84]:
data = [1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20]
test = [20,19,18,17,16,15,14,13,12,11,10,9,8,7,6,5,4,3,2,1]
import numpy as np
from sklearn.model_selection import ShuffleSplit
data = np.array(data)

In [85]:
split = ShuffleSplit(n_splits=5, test_size=1/4, random_state=2)

In [63]:
import pandas as pd
tr1 = pd.DataFrame([])
tr2 = pd.DataFrame([])
tr1['num'] = [1,2]
tr1['word'] = ['one', 'two']
tr2['num'] = [3,4]
tr2['word'] = ['three', 'four']

In [65]:
tr = pd.concat([tr1, tr2], ignore_index=True)
tr

num   word
0    1    one
1    2    two
2    3  three
3    4   four

In [91]:
for train1, train2 in split.split(tr):
    print(train1, 'and', train2)
    print()

[3 1 0] and [2]

[1 3 2] and [0]

[1 2 0] and [3]

[2 1 3] and [0]

[0 2 3] and [1]



In [74]:
pd.concat([tr[2:4], tr])
X = tr['num']
Y = tr['word']

In [79]:
pd.concat([X,Y])
type(X), type(tr)

(pandas.core.series.Series, pandas.core.frame.DataFrame)

In [83]:
X = Y
X, Y

(0      one
 1      two
 2    three
 3     four
 Name: word, dtype: object, 0      one
 1      two
 2    three
 3     four
 Name: word, dtype: object)

In [184]:
from scipy.sparse import *
from scipy import *

row = array([0,0,1,2,2,2])
col = array([0,2,2,0,1,2])
data = array([1,2,3,4,5,6])
A = csr_matrix( [1,2,3])
B = csr_matrix( [4,5,6])
np.append(A.toarray(), B.toarray())

/home/alexkay/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:4: DeprecationWarning: scipy.array is deprecated and will be removed in SciPy 2.0.0, use numpy.array instead
  after removing the cwd from sys.path.
/home/alexkay/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:5: DeprecationWarning: scipy.array is deprecated and will be removed in SciPy 2.0.0, use numpy.array instead
  """
/home/alexkay/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:6: DeprecationWarning: scipy.array is deprecated and will be removed in SciPy 2.0.0, use numpy.array instead
  


array([1, 2, 3, 4, 5, 6], dtype=int64)

In [180]:
hstack((A,B))

/home/alexkay/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:1: DeprecationWarning: scipy.hstack is deprecated and will be removed in SciPy 2.0.0, use numpy.hstack instead
  """Entry point for launching an IPython kernel.


AttributeError: 'numpy.ndarray' object has no attribute 'todense'